
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { UserContextProvider } from "./context/userContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-indigo-600 to-blue-500 min-h-screen`}>
          <UserContextProvider>
            
            <header className="w-full px-6 py-4 bg-purple-700/70 backdrop-blur-md text-white shadow-md">
              <div className="flex items-center gap-3">
                <span className="text-2xl">📝</span>
                <Link href={"/"}><h1 className="text-xl font-bold tracking-wide">RedaAI</h1></Link>
              </div>
            </header>

            {children}
          </UserContextProvider>
        </body>
      </html>
  );
}
